trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SAUCE_USERNAME: 'SAUCE_USERNAME'
  SAUCE_ACCESS_KEY: 'SAUCE_ACCESS_KEY'
  
steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'Default'
    
- task: SauceLabsSecureCredentials@0
  inputs:
    saucelabsUsername: '$(SAUCE_USERNAME)'
    saucelabsAccessKey: '$(SAUCE_ACCESS_KEY)'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export SAUCE_USERNAME=$(SAUCE_USERNAME)
      export SAUCE_ACCESS_KEY=$(SAUCE_ACCESS_KEY)
      
- task: Maven@3
  inputs:
    mavenPomFile: 'best-practice/pom.xml'
    options: '-Dtest=com.saucedemo.tests.PerformanceTests -Dremote.driver.url=<your-sauce-endpoint>/wd/hub -Dremote.platform=Windows 10 -Dremote.browser.name=chrome -Dremote.browser.version=latest -Dremote.execution.type=saucelabs -Dremote.saucelabs.username=$(SAUCE_USERNAME) -Dremote.saucelabs.accessKey=$(SAUCE_ACCESS_KEY)'
    goals: 'clean verify'
