trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    addToPath: true

- task: SauceLabsSecureCredentials@0
  inputs:
    sauceUsername: $(SAUCE_USERNAME)
    sauceAccessKey: $(SAUCE_ACCESS_KEY)

- script: |
    echo Running tests...
    mvn clean test -Dtest=com.saucedemo.tests.PerformanceTests -Dsurefire.forkCount=1 -DtestNgThreadCount=1
  displayName: 'Run PerformanceTests'
  env:
    SAUCE_USERNAME: $(SAUCE_USERNAME)
    SAUCE_ACCESS_KEY: $(SAUCE_ACCESS_KEY)
    SAUCE_ENDPOINT: $(SAUCE_ENDPOINT)
