trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SAUCE_USERNAME: 'SAUCE_USERNAME'
  SAUCE_ACCESS_KEY: 'SAUCE_ACCESS_KEY'
  
steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'Default'
    
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: '<your-artifacts-feed>'
    
- task: Maven@3
  inputs:
    mavenPomFile: 'best-practice/pom.xml'
    options: '-Dremote.driver.url=https://ondemand.saucelabs.com/wd/hub -Dremote.platform=Windows 10 -Dremote.browser.name=chrome -Dremote.browser.version=latest -Dremote.execution.type=saucelabs -Dremote.saucelabs.username=$(SAUCE_USERNAME) -Dremote.saucelabs.accessKey=$(SAUCE_ACCESS_KEY)'
    goals: 'clean verify'
