trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  saucelabsUsername: 'SAUCELABS_USERNAME'
  saucelabsAccessKey: 'SAUCELABS_ACCESS_KEY'

steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '11'
    architecture: 'x64'
    
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'MyFeed'
    
- task: Maven@3
  inputs:
    mavenPomFile: 'best-practice/pom.xml'
    options: '-Dremote.driver.url=https://ondemand.saucelabs.com/wd/hub -Dremote.platform=Windows 10 -Dremote.browser.name=chrome -Dremote.browser.version=latest -Dremote.execution.type=saucelabs -Dremote.saucelabs.username=$(saucelabsUsername) -Dremote.saucelabs.accessKey=$(saucelabsAccessKey)'
    goals: 'clean verify'
