trigger:
- main

pool:
  vmImage: ubuntu-latest

# Multiple pipelines can re-use variables
# that are stored in a variable group
variables:
- group: sauce-labs-variables

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
# Navigate to the working directory
   cd ./webdriverio/webdriver/examples/w3c/
# Install node packages
   npm install
# Run tests on Sauce and enables a high level of logging for CI
   npm run test.saucelabs.us -- --logLevel "debug"
|

 env:
   # Reads the value from 'sauceUsername' in Azure DevOps and
   # stores it into SAUCE_USERNAME env variable
   SAUCE_USERNAME: $(sauceUsername)
   SAUCE_ACCESS_KEY: $(sauceAccessKey)
 displayName: 'install and run WebdriverIO tests in Sauce Labs'